# name: Playwright Tests
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest   
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v4
#       with:
#         node-version: lts/*
#     - name: Install dependencies
#       run: npm ci
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps
#     - name: Run Playwright tests
#       run: npx pwc --key XR2F2iffGibB0VBF --project-id D8CXys
#     - uses: actions/upload-artifact@v4
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30

name: demo.playwright.pwc
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  basicTests:
    strategy:
      fail-fast: false
      # matrix:
      #   # run 3 copies of the job in parallel
      #   shard: [1, 2]

    name: "Playwright Tests - pwc"  
    timeout-minutes: 60
    runs-on: ubuntu-22.04   
    container: mcr.microsoft.com/playwright:latest

    steps:
      - uses: actions/checkout@v4  
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # https://github.com/actions/runner-images/issues/6775
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chrome

     

      - name: Run Project    
        continue-on-error: false  
        
        env:
          CURRENTS_PROJECT_ID: aE3CDD
          CURRENTS_RECORD_KEY: 1abjrR2cNb2B6bAg
        run: |
          npx pwc-p --project=chromium --ci-build-id testid25


     


